# Generated by Django 3.2.3 on 2021-05-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210528_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
