# Generated by Django 3.2.3 on 2021-05-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_books_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
    ]
