# Generated by Django 3.2.3 on 2021-05-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_books_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='India', max_length=200),
        ),
    ]
