# Generated by Django 3.2.3 on 2021-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_remove_cathome_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DurationField(null=True),
        ),
    ]
